In [ ]:
import pandas as pd
import numpy as np
np.random.seed(42)

In [18]:
repayment = np.concatenate([
    np.random.normal(loc=8000, scale=2000, size=190),
    np.random.normal(loc=80000, scale=10000, size=10)
])

In [26]:
df = pd.DataFrame({
    "repayment": 
    repayment
})
df

        repayment
0     8993.428306
1     7723.471398
2     9295.377076
3    11046.059713
4     7531.693251
..            ...
195  83853.173797
196  71161.425638
197  81537.251059
198  80582.087184
199  68570.297022

[200 rows x 1 columns]

In [50]:
# MEASURE OF CENTRAL TENDENCIES

mean_val = df['repayment'].mean()
median_val = df['repayment'].median()
mode_val = df['repayment'].mode()[0]

In [51]:
# MEASURE OF DESPERSION
std = df['repayment'].std()
var = df['repayment'].var()

In [60]:
# PRINTNG THE MEASURES
print("="*40)
print("MEASURES OF CENTERAL TENDENCY")
print("-" * 40)
print(f"Mean:                         PKR {mean_val:,.0f}")
print(f"Median:                       PKR {median_val:,.0f}")
print(f"Mode:                         PKR {mode_val:,.0f}")
print(" "*40)
print("="*40)
print("MEASURES OF DEVIATION")
print("-" * 45)
print(f"Standard Deviation:            PKR {std:,.0f}")
print(f"Variance:                      PKR {var:,.0f}")

========================================
MEASURES OF CENTERAL TENDENCY
----------------------------------------
Mean:                         PKR 11,443
Median:                       PKR 8,136
Mode:                         PKR 2,761

========================================
MEASURES OF DEVIATION
---------------------------------------------
Standard Deviation:            PKR 15,518
Variance:                      PKR 240,796,416

**PROBLEM/PRACTICE**

In [63]:
income = np.array ([25000, 30000, 28000, 35000, 32000, 29000,
27000, 31000, 26000, 500000, 33000, 30000])
df = pd.DataFrame({
    "income": income
})
df

    income
0    25000
1    30000
2    28000
3    35000
4    32000
5    29000
6    27000
7    31000
8    26000
9   500000
10   33000
11   30000

In [67]:
# Centeral tendencies
mean = df['income'].mean()
median = df['income'].median()
mode = df['income'].mode()[0]

# Despersion
variance = df['income'].var()
standard_dev = df['income'].std()

In [73]:
print("="*40)
print("MEASURES OF CENTERAL TENDENCY")
print("-" * 40)
print(f"Mean:                         PKR {mean:,.0f}")
print(f"Median:                       PKR {median:,.0f}")
print(f"Mode:                         PKR {mode:,.0f}")
print(" "*40)
print("="*40)
print("MEASURES OF DEVIATION")
print("-" * 50)
print(f"Standard Deviation:            PKR {standard_dev:,.0f}")
print(f"Variance:                      PKR {variance:,.0f}")

# See the impact of outliers clearly
print(" " * 50)
print("=" * 50)
print("GAP")
print(f"PKR {(mean - median):,.0f}")

========================================
MEASURES OF CENTERAL TENDENCY
----------------------------------------
Mean:                         PKR 68,833
Median:                       PKR 30,000
Mode:                         PKR 30,000

========================================
MEASURES OF DEVIATION
--------------------------------------------------
Standard Deviation:            PKR 135,813
Variance:                      PKR 18,445,242,424

==================================================
GAP
PKR 38,833